### ISSUE TITLE
invalid character in cmd [Version 10.0.14393] on Windows Server 2016

### ISSUE THREAD

**Issue by atleast1eyeblnd** [Neo23x0/log4shell-detector#10]
C:\Users\Administrator\Downloads>python log4shell-detector.py -p C:\windows
  File "C:\Users\Administrator\Downloads\log4shell-detector.py", line 106
    <title>log4shell-detector/log4shell-detector.py at main · Neo23x0/log4shell-detector · GitHub</title>
                                                            ^
SyntaxError: invalid character '·' (U+00B7)

**Comment by deeFIR** [comment]
Did you just right click and save log4shell-detector.py from the front GitHub page? The file you save doing it that way isn't the raw script, and that's why line 106 contains the title tag.

Save this as log4shell-detector.py and try again - https://raw.githubusercontent.com/Neo23x0/log4shell-detector/main/log4shell-detector.py

**Comment by atleast1eyeblnd** [comment]
> Did you just right click and save log4shell-detector.py from the front GitHub page? The file you save doing it that way isn't the raw script, and that's why line 106 contains the title tag.
> 
> Save this as log4shell-detector.py and try again - https://raw.githubusercontent.com/Neo23x0/log4shell-detector/main/log4shell-detector.py

I am such a n00b. Thx man
